version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:  "A first hello"

"I needed to put this filler at the bottom in order for canvas to accept the file. The original file was to small." 
